// Realtime event bus.
//
// This is deliberately an in-process Node EventEmitter, not Redis/Kafka/
// NATS. Per spec section 14: don't introduce an external broker without
// first confirming current scale actually requires it. This backend
// currently runs as a single Render web service process (confirmed: no
// cluster config, no pm2, no multi-instance setup found anywhere in the
// codebase) — an in-process emitter is correct for that today.
//
// THE UPGRADE PATH, if Render is ever scaled to multiple instances: an
// in-process emitter only reaches clients connected to THAT instance.
// An Ops user connected to instance A would miss an event generated by
// telemetry that happened to hit instance B. At that point this file is
// the ONLY thing that needs to change — swap the EventEmitter for a
// Redis pub/sub client with the same emit/on interface — nothing calling
// this module needs to change. That's the entire point of isolating it
// here instead of scattering `emitter.emit(...)` calls everywhere.

const { EventEmitter } = require("events");
const bus = new EventEmitter();
bus.setMaxListeners(0); // many concurrent Ops SSE connections is expected and fine

// Authorized event types only — prevents a typo'd event name from
// silently going nowhere, and gives one place to see the full list spec
// section 15 asks for.
const EVENT_TYPES = new Set([
  "vehicle.location.updated",
  "ride.location.updated",
  "route.changed",
  "route.deviation.started",
  "route.deviation.escalated",
  "route.deviation.resolved",
  "alert.created",
  "alert.updated",
  "vehicle.gps.stale",
  "vehicle.gps.recovered",
]);

function publish(eventType, payload) {
  if (!EVENT_TYPES.has(eventType)) {
    throw new Error(`Unknown event type: ${eventType}. Add it to EVENT_TYPES if this is intentional.`);
  }
  bus.emit(eventType, { type: eventType, payload, publishedAt: new Date().toISOString() });
  bus.emit("*", { type: eventType, payload, publishedAt: new Date().toISOString() });
}

function subscribeAll(handler) {
  bus.on("*", handler);
  return () => bus.off("*", handler);
}

module.exports = { EVENT_TYPES, publish, subscribeAll };
